print("welcome to my chat!!!")
print("dont know what the fuck am i doing wrong...")
print("Closeeeeedddddddddddd!!!!!!!!!!!")
print("Closeeeeedddddddddddd!!!!!!!!!!!")
print("hello elad")
print("bye bye")